### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by joshpfosi** [towerhe/siesta#1]
Hi, is this repo still usable? I only ask as it hasn't been updated in a while. I am experiencing an issue after following the README where it is searching for `/assets/sample.t.js` which is not found. 

Any ideas?

**Comment by towerhe** [comment]
Sorry for my delayed reply. I think this repo can not work well with the modern dev process.

By default, siesta loads your tests from `spec/javascript`. This is done by adding `spec/javascript` to the assets paths of rails. 

``` ruby
# lib/siesta/engine.rb
module Siesta
  class Engine < ::Rails::Engine
    isolate_namespace Siesta

    initializer "siesta.environment" do |app|
      unless app.config.assets.enabled
        raise RuntimeError, "siesta requires the asset pipeline to be enabled"
      end

      app.config.assets.paths << app.root.join(Siesta.config.spec_dir).to_s
    end
  end
end
```

you can change the default path of the tests to your own.

**Comment by joshpfosi** [comment]
Yeah, I actually heavily modified the gem to upgrade Siesta versions and get the paths correct. Ended up not even going with Siesta, but thanks for the response :)
